<?php
declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Leanpay\Payment\Model\Method\Leanpay;
use Leanpay\PaymentHyva\ViewModel\Installments;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Leanpay $method */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var Installments $installments */

$installments = $viewModels->require(Installments::class);
$installmentHtml = $installments->getCheckoutHtml();

$method = $block->getMethod();
?>
<?php /* The wire Payment Method directive is required to sit in the root DOM element. */ ?>
<div>
    <?= /* @noEscape */ $installmentHtml ?>
</div>
