<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
?>
<script>
    function initLeanpayInstallment() {
        return {
            calculatorVisible: false,

            init() {
                console.log('Leanpay Initialized');
            },
            toggleCalculator() {
                this.calculatorVisible = !this.calculatorVisible;
            },
            getCalculatorArrowClasses() {
                return this.calculatorVisible ? 'rotate-180' : '';
            }
        }
    }

    window.addEventListener('alpine:init', () => {
        Alpine.data('initLeanpayInstallment', initLeanpayInstallment);
    }, {once: true});
</script>
<?php isset($hyvaCsp) && $hyvaCsp->registerInlineScript() ?>
